### ISSUE TITLE
Classifier does not work, when text contains "contructor" as token.

### ISSUE THREAD

**Issue by Amberlamps** [ttezel/bayes#6]
The problem is this line: https://github.com/ttezel/bayes/blob/master/lib/naive_bayes.js#L248

```
Naivebayes.prototype.frequencyTable = function (tokens) {
  var frequencyTable = {}

  tokens.forEach(function (token) {
    if (!frequencyTable[token])
      frequencyTable[token] = 1
    else
      frequencyTable[token]++
  })

  return frequencyTable
}
```

When `token` is `"constructor"`, `frequencyTable[token]` is always true, because every object in Javascript natively has the `constructor` property. Therefore `frequencyTable[token]++` runs and this results in `NaN`.

To fix this, we need to check for `if (!frequencyTable.hasOwnProperty(token))`. We will overwrite the `constructor` property, but we do not need it for the object anyway.

**Comment by derhuerst** [comment]
You can also do `Object.create(null)` instead, which should be faster.

**Comment by Amberlamps** [comment]
Yes you are right. However, I think we should do both.

**Comment by ttezel** [comment]
This has been fixed in bayes v0.0.5. Run `npm update twit` to get it! Thanks.

**Comment by Amberlamps** [comment]
You need to apply this also to `this.vocabulary`, `this.docCount`, `this.wordCount`, `this.wordFrequencyCount` and `this.wordFrequencyCount[categoryName]` to be safe.

**Comment by riatzukiza** [comment]
use a `Map` instead, since es6 is a thing now
